#!/bin/ksh

set -e

readonly PROGNAME="`basename $0`"
readonly VERSION='v1.0'

usage() {
	echo "usage: $PROGNAME [-ds] [-t size] file[.b]"
}

dflag=0
sflag=0
tflag=1000
file=''

while getopts ":dst:" opt;do
	case $opt in
		d) dflag=1;;
		s) sflag=1;;
		t) tflag=$OPTARG;;
		:) echo "$PROGNAME: option requires an argument -- $OPTARG";
		   usage; exit 1;;	# NOTREACHED
		?) echo "$PROGNAME: unkown option -- $OPTARG";
		   usage; exit 1;;	# NOTREACHED
		*) usage; exit 1;;	# NOTREACHED
	esac
done
shift $(( $OPTIND -1 ))

if [ -z "$1" ]; then
	echo "$PROGNAME: file expected"
	usage
	exit 1
else
	file="$1"
	shift
fi

if [ $# -ge 1 ]; then
	echo "$PROGNAME: invalid trailing chars -- $@"
	usage
	exit 1
fi

if [ $tflag -le 0 ]; then
	echo "tape size is invalid"
	exit 1
fi

set -u

tape[0]=0
tptr=0
filesize=`cat $file | wc -c`

ic=0
iptr=0

cc=0

move() {
	local index=$(( $tptr + $1 ))

	if [ $index -lt 0 ]; then
		echo "Error: Can't move pointer bellow zero"
		exit 1
	fi

	if [ $index -gt $tflag ]; then
		echo "Error: Reached max tape size"
		exit 1
	fi
	
	if [ $index -ge ${#tape[@]} ]; then
		tape[$index]=0
	fi
	tptr=$index
}

cell() {
	local value="$1"

	tape[$tptr]=$(( ${tape[$tptr]} + $value))
}

output() {
	awk -v v=${tape[$tptr]} 'BEGIN { printf "%c", v; exit }'
}

input() {
	stty raw
	local char="`dd bs=1 count=1 2> /dev/null`"
	stty -raw
	tape[$tptr]=`printf "%d" "'$char"`
}

matchingbrace() {
	local brace="$1"
	local lc=0
	local liptr=$iptr
	local char=0

	if [ "$brace" = "[" ]; then
		openmod='+'
		closemod='-'
	else
		openmod='-'
		closemod='+'
	fi

	while char="`dd if=$file bs=1 count=1 skip=$liptr 2> /dev/null`"; do
		liptr=$(( $liptr $openmod 1 ))
		case $char in
			'[') lc=$(( $lc $openmod 1 ));;
			']') lc=$(( $lc $closemod 1 ));;
			*) continue;;
		esac

		if [ $lc -eq 0 ]; then
			break
		fi
	done
	echo $liptr
}

stats() {
		echo Number of cells used: ${#tape[*]}/$tflag
		echo Number of instructions: $(( $ic - $cc ))
		echo State of the tape: ${tape[*]}
}

trap stats USR1
echo PID: $$ >&2

while i="`dd if=$file bs=1 count=1 skip=$iptr 2> /dev/null`"; do
	[ $iptr -ge $filesize ] && break
	local jump=0
	case $i in
		'<') move -1;;
		'>') move +1;;
		'-') cell -1;;
		'+') cell +1;;
		'.') output;;
		',') input;;
		'[') if [ ${tape[$tptr]} -eq 0 ]; then
			jump=$((`matchingbrace '['` + 1))
		     fi;;
		']') if [ ${tape[$tptr]} -ne 0 ]; then
			jump=`matchingbrace ']'`
		     fi;;
		*) cc=$(( $cc + 1 ));;
	esac
	[ $dflag -eq 1 ] && echo " $i: [$tptr]=${tape[$tptr]}" >&2

	ic=$(( $ic + 1 ))
	iptr=$(( $iptr + 1 ))
done

if [ $sflag -eq 1 ]; then
	stats
fi

